### ISSUE TITLE
请求500

### ISSUE THREAD

**Issue by ikun14514** [Superheroff/musicapi#6]
在win11下运行  
已经安装依赖  
log如下:  
`[2024-07-06 22:26:57,258] ERROR in app: Exception on /music/songlist [GET]
Traceback (most recent call last):
  File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p8877\Desktop\存放各类代码\musicapi\main.py", line 99, in music_songlist
    music_info = musicapi.MusicApi_kuwo(t_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p8877\Desktop\存放各类代码\musicapi\musicapi.py", line 306, in __init__
    self.headers["Secret"] = MusicApi_kuwo_sign().get_Secret(self.cookie)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p8877\Desktop\存放各类代码\musicapi\app.py", line 112, in get_Secret
    return self.kuwojs.call('get_Secret', cookie)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: SyntaxError: 缺少 ';'
127.0.0.1 - - [2024-07-06 22:26:57] "GET /music/songlist?server=wyy&id=4925702668 HTTP/1.1" 500 433 0.498082
[2024-07-06 22:28:44,431] ERROR in app: Exception on /music/songlist [GET]
Traceback (most recent call last):
  File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p8877\Desktop\存放各类代码\musicapi\main.py", line 99, in music_songlist
    music_info = musicapi.MusicApi_kuwo(t_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p8877\Desktop\存放各类代码\musicapi\musicapi.py", line 306, in __init__
    self.headers["Secret"] = MusicApi_kuwo_sign().get_Secret(self.cookie)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p8877\Desktop\存放各类代码\musicapi\app.py", line 112, in get_Secret
    return self.kuwojs.call('get_Secret', cookie)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: SyntaxError: 缺少 ';'
127.0.0.1 - - [2024-07-06 22:28:44] "GET /music/songlist?server=wyy&id=4925702668 HTTP/1.1" 500 433 0.083369
`    

返回是这样的（看起来像html？）：  
`
<!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or
    there is an error in the application.</p>
`  
辛苦看下，谢谢 @Superheroff

**Comment by Superheroff** [comment]
> 在win11下运行  
> 
> 已经安装依赖  
> 
> log如下:  
> 
> `[2024-07-06 22:26:57,258] ERROR in app: Exception on /music/songlist [GET]
> 
> Traceback (most recent call last):
> 
>   File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1473, in wsgi_app
> 
>     response = self.full_dispatch_request()
> 
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 882, in full_dispatch_request
> 
>     rv = self.handle_user_exception(e)
> 
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_cors\extension.py", line 165, in wrapped_function
> 
>     return cors_after_request(app.make_response(f(*args, **kwargs)))
> 
>                                                 ^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 880, in full_dispatch_request
> 
>     rv = self.dispatch_request()
> 
>          ^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 865, in dispatch_request
> 
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\p8877\Desktop\存放各类代码\musicapi\main.py", line 99, in music_songlist
> 
>     music_info = musicapi.MusicApi_kuwo(t_id)
> 
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\p8877\Desktop\存放各类代码\musicapi\musicapi.py", line 306, in __init__
> 
>     self.headers["Secret"] = MusicApi_kuwo_sign().get_Secret(self.cookie)
> 
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\p8877\Desktop\存放各类代码\musicapi\app.py", line 112, in get_Secret
> 
>     return self.kuwojs.call('get_Secret', cookie)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
> 
>     return self._call(name, *args)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\execjs\_external_runtime.py", line 92, in _call
> 
>     return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\execjs\_external_runtime.py", line 78, in _eval
> 
>     return self.exec_(code)
> 
>            ^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
> 
>     return self._exec_(source)
> 
>            ^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\execjs\_external_runtime.py", line 88, in _exec_
> 
>     return self._extract_result(output)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
> 
>     raise ProgramError(value)
> 
> execjs._exceptions.ProgramError: SyntaxError: 缺少 ';'
> 
> 127.0.0.1 - - [2024-07-06 22:26:57] "GET /music/songlist?server=wyy&id=4925702668 HTTP/1.1" 500 433 0.498082
> 
> [2024-07-06 22:28:44,431] ERROR in app: Exception on /music/songlist [GET]
> 
> Traceback (most recent call last):
> 
>   File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1473, in wsgi_app
> 
>     response = self.full_dispatch_request()
> 
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 882, in full_dispatch_request
> 
>     rv = self.handle_user_exception(e)
> 
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask_cors\extension.py", line 165, in wrapped_function
> 
>     return cors_after_request(app.make_response(f(*args, **kwargs)))
> 
>                                                 ^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 880, in full_dispatch_request
> 
>     rv = self.dispatch_request()
> 
>          ^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 865, in dispatch_request
> 
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\p8877\Desktop\存放各类代码\musicapi\main.py", line 99, in music_songlist
> 
>     music_info = musicapi.MusicApi_kuwo(t_id)
> 
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\p8877\Desktop\存放各类代码\musicapi\musicapi.py", line 306, in __init__
> 
>     self.headers["Secret"] = MusicApi_kuwo_sign().get_Secret(self.cookie)
> 
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\p8877\Desktop\存放各类代码\musicapi\app.py", line 112, in get_Secret
> 
>     return self.kuwojs.call('get_Secret', cookie)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
> 
>     return self._call(name, *args)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\execjs\_external_runtime.py", line 92, in _call
> 
>     return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\execjs\_external_runtime.py", line 78, in _eval
> 
>     return self.exec_(code)
> 
>            ^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
> 
>     return self._exec_(source)
> 
>            ^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\execjs\_external_runtime.py", line 88, in _exec_
> 
>     return self._extract_result(output)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\p8877\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
> 
>     raise ProgramError(value)
> 
> execjs._exceptions.ProgramError: SyntaxError: 缺少 ';'
> 
> 127.0.0.1 - - [2024-07-06 22:28:44] "GET /music/songlist?server=wyy&id=4925702668 HTTP/1.1" 500 433 0.083369
> 
> `    
> 
> 
> 
> 返回是这样的（看起来像html？）：  
> 
> `
> 
> <!doctype html>
> 
> <html lang=en>
> 
> <title>500 Internal Server Error</title>
> 
> <h1>Internal Server Error</h1>
> 
> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or
> 
>     there is an error in the application.</p>
> 
> `  
> 
> 辛苦看下，谢谢 @Superheroff 

安装nodejs
